-- ==============================================================================
-- Fieldwork Supabase Schema
-- Run this script in the Supabase SQL Editor.
-- ==============================================================================

-- 1. Custom Types
CREATE TYPE user_role AS ENUM ('student', 'instructor', 'admin');
CREATE TYPE course_status AS ENUM ('draft', 'published', 'archived');
CREATE TYPE enrollment_status AS ENUM ('active', 'completed', 'dropped');
CREATE TYPE ticket_status AS ENUM ('todo', 'in_progress', 'submitted', 'graded');

-- 2. Tables

-- Users table (extends auth.users)
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role user_role NOT NULL DEFAULT 'student',
  full_name TEXT NOT NULL,
  avatar_url TEXT,
  balance NUMERIC(10, 2) DEFAULT 0.00, -- Used for simulated payments/refunds
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Courses table
CREATE TABLE public.courses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instructor_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00, -- The deposit amount
  status course_status NOT NULL DEFAULT 'draft',
  thumbnail_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Course Materials (uploaded by instructor for AI ingestion)
CREATE TABLE public.course_materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
  file_url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_type TEXT,
  content_text TEXT, -- Extracted text for AI processing
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enrollments (Student registering for a course and paying deposit)
CREATE TABLE public.enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
  status enrollment_status NOT NULL DEFAULT 'active',
  amount_paid NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  payment_reference TEXT, -- e.g., M-Pesa transaction ID
  refunded BOOLEAN NOT NULL DEFAULT FALSE,
  refund_amount NUMERIC(10, 2) DEFAULT 0.00,
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  UNIQUE(student_id, course_id)
);

-- Tickets (Simulated real-world tasks generated by AI)
CREATE TABLE public.tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  scenario TEXT NOT NULL, -- The real-world problem description
  deliverables JSONB NOT NULL, -- List of required deliverables
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ticket Submissions (Student's work and AI Review)
CREATE TABLE public.ticket_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.tickets(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  enrollment_id UUID REFERENCES public.enrollments(id) ON DELETE CASCADE NOT NULL,
  status ticket_status NOT NULL DEFAULT 'in_progress',
  student_answer TEXT, -- The student's submitted solution
  ai_feedback TEXT, -- The guided review from the AI
  score NUMERIC(5, 2), -- Optional numerical grade
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_at TIMESTAMPTZ,
  graded_at TIMESTAMPTZ,
  UNIQUE(ticket_id, student_id)
);

-- 3. Row Level Security (RLS)

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_submissions ENABLE ROW LEVEL SECURITY;

-- Users policies
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
-- Admins can view all users (Assuming we create a helper function for admin check, but for simplicity we rely on app-level logic or standard checks)
-- Instructors can view students they teach (simplified here to allow all authenticated users to view public user data like names/avatars)
CREATE POLICY "Public user profiles are viewable by everyone" ON public.users FOR SELECT USING (true);

-- Courses policies
CREATE POLICY "Anyone can view published courses" ON public.courses FOR SELECT USING (status = 'published');
CREATE POLICY "Instructors can view their own courses" ON public.courses FOR SELECT USING (auth.uid() = instructor_id);
CREATE POLICY "Instructors can create courses" ON public.courses FOR INSERT WITH CHECK (auth.uid() = instructor_id);
CREATE POLICY "Instructors can update their own courses" ON public.courses FOR UPDATE USING (auth.uid() = instructor_id);
CREATE POLICY "Instructors can delete their own courses" ON public.courses FOR DELETE USING (auth.uid() = instructor_id);

-- Course Materials policies
CREATE POLICY "Instructors can manage their course materials" ON public.course_materials FOR ALL USING (
  EXISTS (SELECT 1 FROM public.courses WHERE id = course_id AND instructor_id = auth.uid())
);
CREATE POLICY "Enrolled students can view course materials" ON public.course_materials FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.enrollments WHERE course_id = public.course_materials.course_id AND student_id = auth.uid())
);

-- Enrollments policies
CREATE POLICY "Students can view their own enrollments" ON public.enrollments FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Students can create their own enrollments" ON public.enrollments FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Instructors can view enrollments for their courses" ON public.enrollments FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.courses WHERE id = course_id AND instructor_id = auth.uid())
);

-- Tickets policies
CREATE POLICY "Enrolled students can view tickets" ON public.tickets FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.enrollments WHERE course_id = public.tickets.course_id AND student_id = auth.uid())
);
CREATE POLICY "Instructors can manage tickets for their courses" ON public.tickets FOR ALL USING (
  EXISTS (SELECT 1 FROM public.courses WHERE id = course_id AND instructor_id = auth.uid())
);

-- Ticket Submissions policies
CREATE POLICY "Students can manage their own submissions" ON public.ticket_submissions FOR ALL USING (auth.uid() = student_id);
CREATE POLICY "Instructors can view submissions for their courses" ON public.ticket_submissions FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.courses WHERE id = (SELECT course_id FROM public.tickets WHERE id = ticket_id) AND instructor_id = auth.uid())
);

-- 4. Triggers & Functions
-- Trigger to automatically create a user profile when a new auth.users signup occurs
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', COALESCE((new.raw_user_meta_data->>'role')::user_role, 'student'));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==============================================================================
-- Seed Data: Create Default Users in Auth and Public Schema
-- Ensure pgcrypto extension is active to hash passwords (it usually is by default in Supabase)
-- ==============================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
  student_uid UUID := gen_random_uuid();
  instructor_uid UUID := gen_random_uuid();
  admin_uid UUID := gen_random_uuid();
  default_password TEXT := 'password123';
  hashed_password TEXT;
BEGIN
  -- Hash the default password for auth.users
  hashed_password := crypt(default_password, gen_salt('bf'));

  -- 1. Insert Student
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token
  ) VALUES (
    student_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'student@fieldwork.local', hashed_password, now(), now(), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Alice Student","role":"student"}', now(), now(), '', '', '', ''
  );

  -- 2. Insert Instructor
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token
  ) VALUES (
    instructor_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'instructor@fieldwork.local', hashed_password, now(), now(), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Bob Instructor","role":"instructor"}', now(), now(), '', '', '', ''
  );

  -- 3. Insert Admin
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token
  ) VALUES (
    admin_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'admin@fieldwork.local', hashed_password, now(), now(), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Charlie Admin","role":"admin"}', now(), now(), '', '', '', ''
  );

  -- The trigger public.handle_new_user() will automatically insert these users
  -- into public.users with their respective roles and names parsed from raw_user_meta_data.

  -- If you prefer or if the trigger doesn't fire when inserting directly via SQL in some setups,
  -- uncomment the following to force the insertion:
  /*
  INSERT INTO public.users (id, role, full_name) VALUES
    (student_uid, 'student', 'Alice Student'),
    (instructor_uid, 'instructor', 'Bob Instructor'),
    (admin_uid, 'admin', 'Charlie Admin')
  ON CONFLICT (id) DO NOTHING;
  */

END $$;
